# Website settings
baseurl: "/"
url: "http://wangqianwen0418.github.io"
icon: "/assets/img/icons/cat.ico"

# Internal nav
nav:
  main:
    # home: "/"
    research: "/projects"
    experiences: "/experiences"
    # blogs: "/writing"
    photos: "/photos"
  blogs:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Qianwen Wang"
description: "This is the home page of Qianwen Wang, a researcher in Data Visualization and Human-Machine Collaboration."
thumbnail_path: "qianwen.jpg"
# bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
# hello_startup_url: "http://www.hello-startup.net/"
website_repo_url: "https://github.com/wangqianwen0418/"
# atomic_squirrel_url: "http://www.atomic-squirrel.net/"
# gruntwork_url: "http://www.gruntwork.io/"
# terraform_up_and_running_url: "http://www.terraformupandrunning.com/"
# terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  github:
    url: "https://github.com/wangqianwen0418/"
    label: "GitHub"
    icon: "github-square"
  # email:
  #   url: "mailto:qwangbb@connect.ust.hk"
  #   label: "Email"
  #   value: "qwangbb@connect.ust.hk"
  #   icon: "envelope-square"
  email:
    url: "mailto: qianwen_wang@hms.harvard.edu"
    label: "Email"
    value: "qianwen_wang@hms.harvard.edu"
    icon: "envelope-square"
  homepage:
    url: "https://qianwen.info"
    label: "Homepage"
    icon: "home"
  scholar:
    url: "https://scholar.google.com/citations?&user=jtSR4hoAAAAJ"
    label: "Google Scholar"
    icon: "graduation-cap"
  LinkedIn:
    url: "https://www.linkedin.com/in/qianwen-wang-44072bb5/"
    label: "LinkedIn"
    icon: "linkedin-square"
  CV:
    url: assets/pdf/qianwen_cv.pdf
    label: CV
    icon: file

# news
news:
  - label: paper
    title: One paper accepted as oral spotlight presentation by Interpretable Machine Learning in Healthcare workshop, ICML 2021
    date: Jul, 2021
  - label: paper
    title: Two papers accepted by IEEE VIS 2021
    data: Jul, 2021
  - label: talk
    title: Gave two long talks at ISMB 2021
    date: Jul, 2021
  - label: paper
    title: One paper aceepted by ISMB 2021
    date: Mar, 2021
  - label: talk 
    title: Invited talk at PacificVis 2021 Visualization meets AI
    url: http://vis.tju.edu.cn/pvis2021/Invited_talks.html
    date: Apr, 2021
  - label: paper
    title: Three papers accepted by IEEE VIS 2020
    date: Jul, 2020
  - label: job
    title: Started my PostDoc position at Harvard University
    date: May, 2020
  - label: other
    title: Passed my PhD thesis defense!
    date: Dec, 2019
  - label: travel
    title: Visited the University of Oxford, hosted by Prof. Min Chen
    date: Aug-Dec, 2019
  

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
