# Website settings
baseurl: "/"
url: "http://wangqianwen0418.github.io"

# Internal nav
nav:
  main:
    experiences: "/experiences"
    projects: "/projects"
    blogs: "/writing"
    photos: "/photos"
  blogs:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Wang Qianwen"
description: "A home page"
thumbnail_path: "qianwen.jpg"
# bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
# hello_startup_url: "http://www.hello-startup.net/"
website_repo_url: "https://github.com/wangqianwen0418/"
# atomic_squirrel_url: "http://www.atomic-squirrel.net/"
# gruntwork_url: "http://www.gruntwork.io/"
# terraform_up_and_running_url: "http://www.terraformupandrunning.com/"
# terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  github:
    url: "https://github.com/wangqianwen0418/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:qwangbb@connect.ust.hk"
    label: "Email"
    value: "qwangbb@connect.ust.hk"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
