# Website settings
baseurl: "/"
url: "http://www.ybrikman.com"
nav:
  writing: "/writing"
  speaking: "/speaking"
  projects: "/projects"
  photos: "https://plus.google.com/photos/+YevgeniyBrikman/albums"

# Bio settings
name: "Yevgeniy Brikman"
slogan: "Programmer, writer, speaker, traveler"
description: "The home page of Yevgeniy (Jim) Brikman, author of Hello, Startup, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "yevgeniy-brikman-medium.jpg"
bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"

# URLs
hello_startup_url: "http://www.hello-startup.net"
linkedin_url: "https://www.linkedin.com/in/jbrikman"
twitter_url: "https://twitter.com/brikis98"
facebook_url: "https://www.facebook.com/brikis98"
google_url: "https://plus.google.com/+YevgeniyBrikman/"
github_url: "https://github.com/brikis98/"
slideshare_url: "https://www.slideshare.net/brikis98"
stack_exchange_url: "http://stackexchange.com/users/223985/yevgeniy-brikman"
email: "jim@ybrikman.com"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
highlighter: pygments
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap