# Website settings
baseurl: "/"
nav:
  - label: "Writing"
    url: "/writing"
  - label: "Speaking"
    url: "/speaking"
  - label: "Projects"
    url: "/projects"
  - label: "Photos"
    url: "/photos"

# Bio settings
name: "Yevgeniy Brikman"
slogan: "Programmer, writer, speaker, traveler"
description: "The home page of Yevgeniy (Jim) Brikman."
thumbnail: "/assets/img/yevgeniy-brikman-small.jpg"

# URLs
hello_startup_url: "http://www.hello-startup.net"
linkedin_url: "https://www.linkedin.com/in/jbrikman"
twitter_url: "https://twitter.com/brikis98"
facebook_url: "https://www.facebook.com/brikis98"
google_url: "https://plus.google.com/+YevgeniyBrikman/"
github_url: "https://github.com/brikis98/"
slideshare_url: "https://www.slideshare.net/brikis98"
email: "jim@ybrikman.com"

# Jekyll build settings
paginate: 5
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap